services:
  postgres:
    image: postgres:18

    container_name: kitchen_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: kitchen_inventory
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    external: true
    name: docker_postgres_data