"""add unit to pantryitem and recipeingredient

Revision ID: 168eb3bfd741
Revises: 3c3308e99e16
Create Date: 2026-08-04 11:29:18.805177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168eb3bfd741'
down_revision: Union[str, Sequence[str], None] = '3c3308e99e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'unit')
    op.add_column('pantry_items', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('recipe_ingredients', sa.Column('unit', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'unit')
    op.drop_column('pantry_items', 'unit')
    op.add_column('ingredients', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
