"""add ingredient uunit

Revision ID: 3c3308e99e16
Revises: c301f5d3c787
Create Date: 2026-08-04 07:55:43.914165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3308e99e16'
down_revision: Union[str, Sequence[str], None] = 'c301f5d3c787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'unit')
    # ### end Alembic commands ###
