"""add servings_discarded to meal prep model

Revision ID: 4048fc58b228
Revises: b06ee3aae00d
Create Date: 2026-08-27 21:23:59.541555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4048fc58b228"
down_revision: Union[str, Sequence[str], None] = "b06ee3aae00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal_preps",
        sa.Column("servings_discarded",
                  sa.Integer(),
                  nullable=False,
                    server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meal_preps", "servings_discarded")
    # ### end Alembic commands ###
