"""add base servings to recipe

Revision ID: bc651273fb09
Revises: 168eb3bfd741
Create Date: 2026-08-14 11:26:51.121156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc651273fb09'
down_revision: Union[str, Sequence[str], None] = '168eb3bfd741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('base_services', sa.Integer(), nullable=False, server_default="1",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'base_services')
    # ### end Alembic commands ###
